### ISSUE TITLE
3.1 release TODO

### ISSUE THREAD

**Issue by kirs** [capistrano/capistrano#813]
- [ ] As :restart is not invoked on deploy, I've run into a problem after upgrading 3.0.1 to 3.1. I forgot to add `after :publishing, :restart` and my Puma didn't restart :( I think we really should notify users about that somehow.
- [ ] release doc should describe that 3.0 had issues with mapping rbenv/rvm/bundler commands and this was totally fixed in 3.1
- [ ] don't forget to mention @Kriechi 's help
